version: '3.1'

services:
  siugj:
    build:
     context: .
    restart: always
    volumes:
      - /mnt/e/E/Proyectos consultoria/Rama Judicial/LinkTic/Software/SIUGJ_Colombia/rama_dev_siugj/html:/var/www/html
    ports:
      - 80:80

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  taskCheck:
    image: marioegc/siugjtask:02
    restart: always
    environment:
      - urlSite=http://siugj/
      - TimeCheckTask=300

